yarn e2e-areaChart
yarn e2e-barChart
yarn e2e-circularLinearWithBrush
yarn e2e-circularVisualEncoding
yarn e2e-ideogram
yarn e2e-lineChart
yarn e2e-multiTrackApp
yarn e2e-pointPlot
yarn e2e-ruleMarks
yarn e2e-sarsCov2
yarn e2e-staticCircularBar
yarn e2e-structuralVariant
yarn e2e-textAnnotation
yarn e2e-textMarks
