---
title: "Marking area in shiny.gosling"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to shiny.gosling}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
runtime: shiny
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo = FALSE}
library(shiny.gosling)
library(shiny)
library(sessioninfo)
```

# Marking area in a simple shiny.gosling plot

```{r, eval = FALSE}
ui <- fluidPage(
  use_gosling(),
  goslingOutput("gosling_plot")
)
server <- function(input, output, session) {
  output$gosling_plot <- renderGosling({
    gosling(
      component_id = "component_1",
      arrange_views(
        title = "Basic Marks: area",
        subtitle = "Tutorial Examples",
        views = compose_view(
          tracks = add_single_track(
            layout = "linear",
            width = 800,
            height = 180,
            data = track_data(
              url = "https://resgen.io/api/v1/tileset_info/?d=UvVPeLHuRDiYA3qwFlm7xQ",
              type = "multivec",
              row = "sample",
              column = "position",
              value = "peak",
              categories = list("sample 1")
            ),
            mark = "area",
            x = visual_channel_x(field = "position", type = "genomic", axis = "bottom"),
            y = visual_channel_y(field = "peak", type = "quantitative", axis = "right"),
            size = visual_channel_size(value = 2)
          )
        )
      )
    )
  })
}
shiny::shinyApp(ui, server)
```

```{r, echo = FALSE}
library(htmltools)
tags$div(
  class = "shiny-app-frame",
  tags$iframe(src = "https://connect.appsilon.com/shiny-gosling-area/", width = 950, height = 350)
)
```
