---
title: 'Introduction to shiny.gosling'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to shiny.gosling}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Introduction to shiny.gosling

This package is an R shiny implementation of the [**Gosling.js**](http://gosling-lang.org/) library. Gosling js is a highly _expressive_ library based on a _Grammer for scalable and interactive Gnenomics Data visualization_. This library is build upon the [**React** wrapper of the Gosling.js](https://github.com/gosling-lang/gosling-react). Which is powered by [**Shiny.React**](https://github.com/gosling-lang/gosling-react). Thus most of the Charts can be directly build using this package.

Let's start with an example. For that let's read a csv file which has some Genomic data with chromosome start stop indicators. This dataset is directly picked from github [here](https://github.com/sehilyi/gemini-datasets). You can read more about the dataset by going to there website [here](https://gemini.readthedocs.io/en/latest/index.html). In short GEMINI (GEnome MINIng) is a flexible framework for exploring genetic variation in the context of the wealth of genome annotations available for the human genome.

```{r}
scanb_filepath <- sprintf(
  fmt = "%s/examples/multiTrackApp/data/gemini_multitrack_2_data.csv",
  system.file(package = "shiny.gosling")
)
```
