---
title: "Marking text in shiny.gosling"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to shiny.gosling}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
runtime: shiny
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(shiny.gosling)
library(shiny)
library(sessioninfo)
```

# Plotting a simple text plot

```{r, echo = FALSE}
ui <- fluidPage(
  use_gosling(),
  goslingOutput("gosling_plot")
)
server <- function(input, output, session) {
  output$gosling_plot <- renderGosling({
    gosling(
      component_id = "component_1",
      arrange_views(
        title = "Basic Marks: text",
        subtitle = "Tutorial Examples",
        views = compose_view(
          tracks = add_single_track(
            layout = "linear",
            width = 800,
            height = 180,
            data = track_data(
              url = "https://resgen.io/api/v1/tileset_info/?d=UvVPeLHuRDiYA3qwFlm7xQ",
              type = "multivec",
              row = "base",
              column = "position",
              value = "count",
              categories = list("A", "T", "G", "C"),
              start = "start",
              end = "end",
              binSize = 16
            ),
            mark = "text",
            y = visual_channel_y(field = "count", type = "quantitative"),
            style = list(textStrokeWidth = 0),
            streach = list(TRUE),
            x = visual_channel_x(field = "start", type = "genomic", axis = "top"),
            xe = visual_channel_x(field = "end", type = "genomic"),
            color = visual_channel_color(
              field = "base",
              type = "nominal",
              domain = list("A", "T", "G", "C")
            ),
            text = visual_channel_text(field = "base", type = "nominal")
          )
        )
      )
    )
  })
}
shiny::shinyApp(ui, server)
```

```{r, echo = FALSE}
library(htmltools)
tags$div(
  class = "shiny-app-frame",
  tags$iframe(src = "https://connect.appsilon.com/shiny-gosling-text/", width = 950, height = 350)
)
```
