---
name: BiocCheck

on: push

jobs:
  bioccheck:
    runs-on: ubuntu-latest
    name: BiocCheck
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          http-user-agent: release
          use-public-rspm: true

      - name: Install Deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: false
          pak-version: 'devel'

      - name: Install shiny.react with React 18.3.1
        if: always()
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e 'install.packages("remotes"); remotes::install_github("Appsilon/shiny.react")'

      - name: Run BiocCheck
        uses: Appsilon/bioc-check-action@v1.2
        with:
          new-package: true
          no-cache: true
          allow-failure: true
