name: Cypress Tests

on: push

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          # Disable running of tests within install job
          runTests: false
      
      - name: Install node dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: tests/yarn.lock
      - run: yarn install

  cypress-run:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          needs: check
          pak-version: 'devel'
          extra-packages: local::. # Necessary to avoid object usage linter errors.
      
      - name: Cypress Run
        uses: cypress-io/github-action@v5
        with:
          start: yarn e2e-areaChart
